<?xml version="1.0"?>
<robot name="Legendary-Waffle" xmlns:xacro="http://ros.org/wiki/xacro"
            xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
            xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
            xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <xacro:include filename="plugins.xacro"/>

  <!-- DEFINING GENERIC PROPERTIES THAT ARE USED IN THE XACRO FILE -->

  <!-- along x axis -->
  <xacro:property name="base_length" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="base_width" value="0.5"/>
  <!-- along z axis -->
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_mass" value="5"/>
  <xacro:property name="wheel_dia" value="0.1"/>
  <xacro:property name="wheel_height" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.5"/>

  <!-- COLOURS FOR MATERIAL -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba ="0 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <!-- MACROS FOR INERTIAL PROPERTIES -->
  <xacro:macro name="base_inertial">
    <inertial>
      <mass value="${base_mass}" />
      <inertia ixx="${(1/12)*base_mass*((base_width*base_width)+(base_height*base_height))}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12)*base_mass*((base_height*base_height)+(base_length*base_length))}"
        iyz="0.0"
        izz="${(1/12)*base_mass*((base_width*base_width)+(base_length*base_length))}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel_inertial">
    <inertial>
      <mass value="${wheel_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>


  <!-- MACRO FOR GENERIC WHEEL. SUPPLY PARAMS TO PLACE THEM, JOINT INCLUDEDE IN MACRO -->
  <xacro:macro name="wheel" params="left_right front_back relx rely">
    <link name="${left_right}_${front_back}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial/>
    </link>

    <joint name="${left_right}_${front_back}_wheel_to_base_link" type="continuous">
      <origin xyz="${relx*((base_length/2)-wheel_dia/2)} ${rely*((base_width/2-wheel_height/2))} ${wheel_dia/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${left_right}_${front_back}_wheel"/>
    </joint>
  </xacro:macro>
  
  <!-- BASE LINK. MAIN BOX TO WHICH WHEEL AND EVERYTHING ELSE IS TO BE ATTACHED -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${wheel_dia + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_dia + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:base_inertial/>
  </link>

  <!-- CREATING AN INSTANCE OF EACH WHEEL -->
  <!-- ADD 4 WHEELS TO THE ABOVE BOT HERE -->
</robot>
